###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:5.7'
        working_dir: /application
        volumes:
            - './www:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=biblioteca
            - MYSQL_USER=antonio
            - MYSQL_PASSWORD=123456
        ports:
            - '44002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './www:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '44000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - './www:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
